2025-10-08 04:04:17 UTC
Windows-11-10.0.26100-SP0
Ren'Py 8.4.1.25072401

Early init took 62 ms
Loading error handling took 74 ms
Loading script took 367 ms
Loading save slot metadata took 96 ms
Loading persistent took 0 ms
Running init code took 262 ms
Loading analysis data took 16 ms
Analyze and compile ATL took 2 ms
Reloading save slot metadata took 48 ms
Backing up script files to 'C:\\Users\\user\\AppData\\Roaming/RenPy/backups\\SpeechPerfect':
Dump and make backups took 56 ms
Cleaning cache took 0 ms
Making clean stores took 0 ms
Initial gc took 69 ms
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b"Couldn't load nvlib." (can be ignored)
Creating interface object took 4 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 18 ms
Analyze screens took 64 ms
Save screen analysis took 111 ms
Save pyanalysis took 7 ms
Save bytecode took 40 ms
Running _start took 2 ms
Interface start took 1624 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 22.20.42.02.221103'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1080, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(898, 505) drawable=(898, 505)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(958, 981) drawable=(958, 981)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(898, 505) drawable=(898, 505)
Maximum texture size: 4096x4096
Error fetching emotion: HTTPSConnectionPool(host='humancc.site', port=443): Max retries exceeded with url: /ndhos/renpy_backend/http_get_emotions.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000000008e2e5a0>, 'Connection to humancc.site timed out. (connect timeout=5)'))
Error fetching emotion: HTTPSConnectionPool(host='humancc.site', port=443): Read timed out. (read timeout=5)
Error fetching emotion: HTTPSConnectionPool(host='humancc.site', port=443): Read timed out. (read timeout=5)
Error fetching emotion: HTTPSConnectionPool(host='humancc.site', port=443): Read timed out. (read timeout=5)
Error fetching emotion: HTTPSConnectionPool(host='humancc.site', port=443): Read timed out. (read timeout=5)
Cleaning stores took 0 ms
Load screen analysis took 22 ms
Analyze screens took 0 ms
Running _start took 1 ms
